serverFiles:
  alerting_rules.yml:
    groups:
    - name: Node
      rules:
      - alert: NodeDown
        expr: up{job="kubernetes-nodes"} == 0
        for: 1m
        annotations:
          description: kubernetes node {{ .Labels.instance }} down